// <auto-generated />
using Fragrantica.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fragrantica.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250114215959_addProductToDb")]
    partial class addProductToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fragrantica.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Eau de Parfum"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Parfum"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Eau de Toilette"
                        });
                });

            modelBuilder.Entity("Fragrantica.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfumeHouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Elegant fragrance with woody notes",
                            ImageUrl = "",
                            Name = "Cedrat Boise",
                            PerfumeHouse = "Mancera",
                            Price = 120.0,
                            SerialNumber = "4589ABD12"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Elegant fragrance with woody and green notes",
                            ImageUrl = "",
                            Name = "Hindu Kush",
                            PerfumeHouse = "Mancera",
                            Price = 150.0,
                            SerialNumber = "4589AFC15"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Elegant fragrance with fresh citrusy notes",
                            ImageUrl = "",
                            Name = "Sculpture",
                            PerfumeHouse = "Nikos",
                            Price = 45.0,
                            SerialNumber = "8219GBK12"
                        });
                });

            modelBuilder.Entity("Fragrantica.Models.Product", b =>
                {
                    b.HasOne("Fragrantica.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
